apiVersion: v1
kind: Secret
metadata:
  name: datalake-secrets
  namespace: nexoryx-datalake
type: Opaque
stringData:
  POSTGRES_DB: metastore
  POSTGRES_USER: hive
  POSTGRES_PASSWORD: CHANGE_ME
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: CHANGE_ME
